### ISSUE TITLE
发不了群聊图片

### ISSUE THREAD

**Issue by Alanzhuo** [wpyok168/XiaoLiZi_SDK#3]
发不了群聊图片，效果如下图
![1612419622(1)](https://user-images.githubusercontent.com/22291859/106853169-3dcf9600-66f4-11eb-80ef-0f13beff83fa.jpg)
![@17JXBQ1S$RG6OPJ1T9S@D9](https://user-images.githubusercontent.com/22291859/106853172-3f995980-66f4-11eb-8b03-22671d9d8057.png)

**Comment by wpyok168** [comment]
已处理 cartoon=false
